state_validity_checker:
  type: "uav_and_wp_manipulator"
  uav_wp_manipulator:
    robot_model_name: "wp_manipulator"
    joint_group_name: "wp_manipulator_arm"
    dh_parameters_file: "catkin_ws/src/aerial_manipulators/aerial_manipulators_control/config/wp_manipulator_dh_parameters.yaml"

    manipulator_link_dimensions: [[0.0340, 0.1225, 0.0285], [0.1365, 0.0340, 0.0285], [0.0755, 0.0285, 0.0340], [0.0725, 0.0285, 0.0340], [0.0453, 0.0285, 0.0340]]
    manipulator_link_directions: ["y", "x", "x", "x", "x"]

    uav_dimensions: [0.4, 0.4, 0.17]

    uav_manipulator_transform: [0, 0, 0.075, 1.57079632679, 0, 3.14159265359]

    checker_resolution:
      manipulator: 0.01
      uav: 0.03

    tool:
      use_tool: true
      dimensions: [0.3453, 0.01, 0.01]
      direction: "x"