global_planner:
  map_config_file: "catkin_ws/src/larics_motion_planning/startup/multiple_manipulators/5dof_4dof/custom_config/heterogeneous_5dof_4dof_object_planner_config.yaml"
  trajectory_config_file: "catkin_ws/src/larics_motion_planning/startup/multiple_manipulators/5dof_4dof/custom_config/heterogeneous_5dof_4dof_object_planner_config.yaml"
  path_planner_config_file: "catkin_ws/src/larics_motion_planning/startup/multiple_manipulators/5dof_4dof/custom_config/heterogeneous_5dof_4dof_object_planner_config.yaml"
  state_validity_checker_config_file: "catkin_ws/src/larics_motion_planning/startup/multiple_manipulators/5dof_4dof/custom_config/heterogeneous_5dof_4dof_object_planner_config.yaml"
  # Kinematics and model corrections are within the
  # uav planner file
  kinematics_config_file: "catkin_ws/src/larics_motion_planning/startup/multiple_manipulators/5dof_4dof/custom_config/heterogeneous_5dof_4dof_planner_config.yaml"
  model_correction_file: "catkin_ws/src/larics_motion_planning/startup/multiple_manipulators/5dof_4dof/custom_config/heterogeneous_5dof_4dof_planner_config.yaml"

  trajectory:
    restarts: 5

  path_and_trajectory:
    restarts: 5

  path:
    restarts: 5
    collision_check_restarts: 5
    collision_check: true

  parabolic_airdrop:
    # Parabola family parameters.
    # d is dropoff distance projected onto xy plane
    d: [3.0, 3.0, 2.0, 3.5, 1.5, 4.0, 1.0, 4.5, 5.0, 5.5, 6.0]
    # v is linear speed of the projectile in airdrop direction
    v: [3.0, 3.0, 2.0, 3.5, 1.5, 4.0, 1.0, 4.5, 5.0, 5.5, 6.0]
    # alpha is angle at which the projectile is launched
    alpha: [0.0, 25.0, 15.0, 30.0, 10.0, 5.0, 0.0, 35.0, 40.0, 45.0]
    # We search for all 360 degrees for the direction of parabola. This 
    # parameter defines increment in degrees
    yaw_increment: 90 #22.5
    # Maximum difference in height between dropoff and final parabola point.
    # Candidates with larger difference will be discarded.
    max_dz: 50
    # Parabola is planned for payload which is typically below the vehicle.
    # That's why we have offset in z-axis while planning the trajectory for
    # the uav.
    payload_z_offset: 0.1

    # Stopping trajectory parameters [x, y, z, yaw]
    stopping_velocity: [8, 8, 3, 2]
    stopping_acceleration: [2, 2, 1, 2.0]
    use_horizontal_stopping_acceleration: false
    horizontal_stopping_acceleration: 4.0
    # Dropoff trajectory parameters [x, y, z, yaw]
    dropoff_velocity: [4, 4, 3, 2]
    dropoff_acceleration: [1.5, 1.5, 1, 1.0]
    use_horizontal_dropoff_acceleration: false
    horizontal_dropoff_acceleration: 2.0
    # Max line integral for dropoff trajectory is the max length of toppra
    # trajectory that is going to be replaced with the dropoff spline
    max_line_integral: 5.0
    # Common for both trajectories is acceleration between dropoff and stopping
    # trajectories. The idea is to have a positive z-direction acceleration so
    # the uav does not interact with dropped object. [x, y, z, yaw]
    intermediate_acceleration: [0, 0, 0, 0]
    use_horizontal_intermediate_acceleration: false
    horizontal_intermediate_acceleration: 1.0

    spline_sampling_time: 0.01

octomap:
  path_to_file: "catkin_ws/src/larics_motion_planning/config/empty_map.binvox.bt"
  search_depth: 14

path_planner:
  spaces:
    number: 2
    # Object [x,y,z,roll,pitch], Object [yaw], [manipulator] -> x2
    dimensions: [5, 1]
    weights: [1.0, 0.1]
    types: ["RealVector", "SO2"]
    bounds: [[[-3, 1.0], [-10.0, 10.0], [0.2, 3.0], [0.0, 0.0], [-0.2, 0.2]], [[-3.15, 3.15]]]
  longest_valid_segment:
    is_used: true
    is_metric: true
    value: 0.5
  goal_bias:
    is_used: true
    value: 0.05
  range:
    is_used: true
    value: 0.25
  rewire_factor:
    is_used: false
    value: 1.1
  delay_cc:
    is_used: true
    value: true
  tree_pruning: 
    is_used: true
    value: false
  prune_threshold:
    is_used: true
    value: 0.1
  pruned_measure:
    is_used: true
    value: false
  k_nearest:
    is_used: true
    value: true
  solve_time:
    is_incremental: true
    time: 5.0
    increment: 1.0
  path_simplifier:
    reduce_vertices:
      is_used: true
      max_steps: 0.25
      max_empty_steps: 0
      range_ratio: 0.33
      use_as_fraction: true
    smooth_b_spline:
      is_used: true
      max_steps: 5

trajectory_planner:
  constant_velocity_reparametrization:
    axes_index_list: []
    velocity_constraints: []
  toppra_trajectory:
    velocities:    [0.2, 0.2, 0.2, 0.2, 0.2, 0.2]
    accelerations: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
    # This flag is important because it preconditiones angular values before 
    # sending them to toppra trajectory. The problem is that toppra does not know
    # for discontinuities at half circle (PI) and the planned trajectory will
    # turn around the circle instead through discontinuity. This flag solves it
    # by adding and subtracting k*2PI around the discontinuity.
    is_angular: [0, 0, 0, 0, 0, 1]
    sampling_frequency: 100.0

state_validity_checker:
  type: "multiple_manipulators"
  object_checker:
    is_used: true
    resolution: 0.025
    # Object will be considered a prism for now.
    dimensions: [0.3, 0.05, 0.05]


  multiple_manipulators:
    - # Wp manipulator
      manipulator_link_dimensions: [[0.0340, 0.1225, 0.0285], [0.1365, 0.0340, 0.0285], [0.0755, 0.0285, 0.0340], [0.0725, 0.0285, 0.0340], [0.0453, 0.0285, 0.0340]]
      manipulator_link_directions: ["y", "x", "x", "x", "x"]

      base_dimensions: [0.7, 0.7, 0.3]
      base_dof: 6
      base_manipulator_transform: [0, 0, 0.075, 1.57079632679, 0, 3.14159265359]

      checker_resolution:
        manipulator: 0.01
        base: 0.03

      tool:
        use_tool: false
        dimensions: [0.3453, 0.01, 0.01]
        direction: "x"

      indexes:
        start: 0
        end: 10
    -
      # Asap manipulator 4r
      manipulator_link_dimensions: [[0.17955, 0.0285, 0.0340], [0.1015, 0.0285, 0.0340], [0.151, 0.0285, 0.0340], [0.048, 0.0285, 0.0340]]
      manipulator_link_directions: ["y", "x", "x", "x"]

      base_dimensions: [0.7, 0.7, 0.3]
      base_dof: 6
      base_manipulator_transform: [0, 0, -0.2, 0, 0, 0]

      checker_resolution:
        manipulator: 0.01
        base: 0.03

      tool:
        use_tool: false
        dimensions: [0.3453, 0.01, 0.01]
        direction: "x"

      indexes:
        start: 11
        end: 20