trajectory_handler:
  -
    type: "UavAndWpManipulatorHandler"
    namespace: "model_uav1"
    uav_topic: "trajectory_point_ref"
    manipulator_topics: ["joint1_position_controller/command", "joint2_position_controller/command",
      "joint3_position_controller/command", "joint4_position_controller/command", 
      "joint5_position_controller/command"]
    indexes:
        start: 0
        end: 10
  -
    type: "UavAndWpManipulatorHandler"
    namespace: "model_uav2"
    uav_topic: "trajectory_point_ref"
    manipulator_topics: ["joint1_position_controller/command", "joint2_position_controller/command",
      "joint3_position_controller/command", "joint4_position_controller/command", 
      "joint5_position_controller/command"]
    indexes:
        start: 11
        end: 21